name: CI

env:
  GO_VERSION: "1.25"
  PLATFORM_CI_REF: "v1.3.0"

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    uses: sangrita-tech/platform-ci/.github/workflows/lint.yml@${{ env.PLATFORM_CI_REF }}
    permissions:
      contents: read
    secrets: inherit
    with:
      go_version: ${{ env.GO_VERSION }}

  test:
    uses: sangrita-tech/platform-ci/.github/workflows/test.yml@${{ env.PLATFORM_CI_REF }}
    permissions:
      contents: read
    secrets: inherit
    with:
      go_version: ${{ env.GO_VERSION }}

  vuln-scan:
    uses: sangrita-tech/platform-ci/.github/workflows/scan-vulns.yml@${{ env.PLATFORM_CI_REF }}
    permissions:
      contents: read
      security-events: write

  secrets-scan:
    uses: sangrita-tech/platform-ci/.github/workflows/scan-secrets.yml@${{ env.PLATFORM_CI_REF }}
    permissions:
      contents: read
      security-events: write
