name: Release

env:
  GO_VERSION: "1.25"
  PLATFORM_CI_REF: "v1.3.0"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    uses: sangrita-tech/platform-ci/.github/workflows/release.yml@${{ env.PLATFORM_CI_REF }}
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      go_version: ${{ env.GO_VERSION }}
